language: objective-c
before_install:
    - brew update
    - brew install xctool --HEAD
    - mkdir -p TransitionKit.xcodeproj/xcshareddata/xcschemes && cp Tests/Schemes/*.xcscheme TransitionKit.xcodeproj/xcshareddata/xcschemes/
script: rake spec
